apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-page-v4
  namespace: shopping-page
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-page-v4
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: landing-page-v4
  namespace: landing-page
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: landing-page-v4
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: watch-page-v4
  namespace: watch-page
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: watch-page-v4
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0


